services:
  api:
    build:
      dockerfile: Dockerfile-test
      context: .
    depends_on:
      - mysql
    restart: on-failure:10
    environment:
      TESTING: true
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_USER_PASS: Password
      MYSQL_DATABASE_NAME: backend
      MYSQL_TEST_DATABASE_NAME: backend-test
      PORT: 3005
    ports:
      - '8090:3005'
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: backend-test
      MYSQL_ROOT_PASSWORD: Password
    ports:
      - '3307:3306'
