services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
    command: sh -c './wait-for mysql:3306 -- npm run migration:run && npm run start'
    depends_on:
      - mysql
    restart: on-failure:10
    environment:
      TESTING: 'false'
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_USER_PASS: Password
      MYSQL_DATABASE_NAME: backend
      PORT: 3000
    ports:
      - '8080:3000'
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: backend
      MYSQL_ROOT_PASSWORD: Password
    ports:
      - '3307:3306'
